[project]
name = "yt-subs"
version = "0.1.0"
description = "A Python library that makes it easy to download any YouTube subtitle in any available format."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["yt-dlp[default]>=2026.3.17"]

[dependency-groups]
dev = ["pytest>=9.0.3", "ruff>=0.15.15", "ty>=0.0.42"]

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
